### ISSUE TITLE
EnumProcessor

### ISSUE THREAD

**Issue by shanielh** [Code-Sharp/GraphClimber#2]
Should the EnumProcessor include two methods, One for processing enums that are boxed and one for processing enums that aren't boxed?

Or should we split it to two interfaces : IEnumProcessor, IBoxedEnumProcessor?

Shani.

**Comment by yoniiny** [comment]
Why should there be two implementations? There should be just one interface and one method, and lots of work in the background that makes everything fit together when it's boxed.

**Comment by shanielh** [comment]
last graph climber processor's had a lot of "if (else)" in their code due to problems like these. 

We can have an interface for simple use, But then we can't give a ValueDescriptor<T> as a parameter (due to the Get method, That returns T and maybe other object that is not of the enum type). We may give a something that is similiar to the value descriptor that has no get method :(

**Comment by yoniiny** [comment]
The problem is when T is object or Enum or nullable enum, right? Can you give a use case that showcases the problem?
It definitely doesn't make sense to expose this complexity to the user. We managed to solve it twice already, no reason to make things ugly now :)

**Comment by shanielh** [comment]
I suggest we do two interfaces. For simple and power users. And implement the simple interface first in the development stage. 

שני.

**Comment by shanielh** [comment]
Fixed by @darkl .
